### ISSUE TITLE
Language failed: metadata.json is missing 

### ISSUE THREAD

**Issue by Padina42** [fulgor/q2a-lang-de-formal#10]
{
	"name": "Deutsch (DE)"
}

The file should contain the code above.

**Comment by fulgor** [comment]
Hello Padina42, there is no file **metadata.json** in q2a-language-packs. I also checked with the [French translation](https://github.com/mrflos/q2a-lang-fr). Do you have a reference? 
Regards

**Comment by Padina42** [comment]
I have no reference only experience.
 I copied q2a(1.8.3) in the webfolder /argumente/ and all your translation files in the web-folder /argumente/qa-lang/de-DE/. The Installation worked, but i could not install your translation. 
The main-code contains an folder with /qa-lang/en-GB/. That folder had an file metadata.json.
After integration of file metadata.json in my de_DE-Folder I could select the german language and activate it for the system.

**Comment by fulgor** [comment]
Thank you! The folder's name is supposed to be `de` not `de-DE`.
Your solution follows the example of `en-EN`. This languagepack does have a file `metadata.json`, which according to a comment to the respective function 
`qa_admin_language_options()` in file `qa-include/app/admin.php` is deprecated.
However, `metadata.json` still works and offers a possibility to indicate whether Du-Form or Sie-Form is meant. Thus, I will add a `metadata.json` file.
